apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: janusguards.januscontroller.clustergarage.io
spec:
  group: januscontroller.clustergarage.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: JanusGuard
    singular: janusguard
    plural: janusguards
    shortNames:
    - jg
    categories:
    - all
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Observable
    type: integer
    description: Number of pods that can be guarded
    JSONPath: .status.observablePods
  - name: Guarded
    type: integer
    description: Number of pods currently being guarded
    JSONPath: .status.guardedPods
